# Generated by Django 6.1.1 on 2026-09-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cultura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_plantio", models.DateField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="areas.area"
                    ),
                ),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
                "ordering": ["nome"],
            },
        ),
    ]
